const fonts = {
  family: {
    proximaRegular: 'ProximaNova-Regular',
    proximaLight: 'ProximaNova-Light',
    proximaBold: 'ProximaNova-Bold',
    proximaSemiBold: 'ProximaNova-Semibold',
    novecentoRegular: 'Novecentosansnarrow-Regular',
    novecentoBold: 'Novecentosansnarrow-Bold',
    novecentoSemibold: 'Novecentosansnarrow-Semibold',
    novecentoLight: 'Novecentosansnarrow-Light',
    novecentoUltraBold: 'Novecentosansnarrow-UltraBold',
  },
  sizes: {
    xs: 8,
    sm: 10,
    md: 12,
    lg: 14,
    xl: 16,
    '2xl': 18,
    '3xl': 20,
    '4xl': 22,
    '5xl': 24,
    '6xl': 26,
    '7xl': 28,
    '8xl': 30,
    '9xl': 32,
    '10xl': 34,
    '11xl': 36,
    '12xl': 40,
    '13xl': 44,
    '14xl': 48,
    '15xl': 52,
    '16xl': 56,
    '17xl': 60,
    '18xl': 64,
    '19xl': 68,
    '20xl': 70,
  },
};

export default fonts;
